name: Test — Reusable Hello v3

on:
  workflow_call:
    inputs:
      has-tests:
        required: false
        type: boolean
        default: true
      tests-continue-on-error:
        required: false
        type: boolean
        default: false
      service-dir:
        required: true
        type: string
    secrets:
      SONAR_TOKEN:
        required: true

jobs:
  test:
    name: Hello v3
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Python
        if: ${{ inputs.has-tests }}
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
          cache: 'pip'
          cache-dependency-path: '${{ inputs.service-dir }}/requirements.txt'

      - name: Fake test step
        if: ${{ inputs.has-tests }}
        working-directory: ${{ inputs.service-dir }}
        continue-on-error: ${{ inputs.tests-continue-on-error }}
        run: echo "running tests"

      - name: Summary step
        if: always()
        working-directory: ${{ inputs.service-dir }}
        run: echo "done"
