name: Test — Reusable Hello v8

on:
  workflow_call:
    inputs:
      service-dir:
        required: true
        type: string
    secrets:
      SONAR_TOKEN:
        required: true

jobs:
  test:
    name: Tests & SonarQube
    runs-on: ubuntu-latest
    timeout-minutes: 30
    permissions:
      checks: write
      contents: read
      security-events: write
      actions: read

    steps:
      - uses: actions/checkout@v4
      - run: echo "done in ${{ inputs.service-dir }}"
